name: sample

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  connectivity_plus:
  # google_fonts: ^6.2.1
  flutter_riverpod:
  http:
  shared_preferences:
  intl:
  firebase_core:
  firebase_auth:
  firebase_analytics:
  firebase_messaging:
  cached_network_image:
  permission_handler:
  url_launcher:
  package_info_plus:
  device_info_plus:
  logger:
  # awesome_notifications: ^0.8.2
  flutter_svg: ^1.1.6
  dropdown_search: ^5.0.5
  xml:
  encrypt:
  hex:
  flutter_styled_toast:
  wave:
  fluttertoast:
  liquid_pull_to_refresh:
  hive:
  # hive_flutter:
  path_provider:
  open_file:
  blinking_text:
  file_picker:
  flutter_pdfview:
  printing:
  pdf:
  flutter_cached_pdfview:
  excel:
  flicked_cards: ^0.0.3
  flutter_neumorphic:
  # animated_cards_carousel:
  carousel_slider:
  sidebarx:
  percent_indicator:
  flutter_zoom_drawer:
  badges:
  fl_chart: ^0.71.0
  flutter_animate:
  table_calendar:
  graphic:
  pie_chart:
  flutter_launcher_icons: ^0.14.3
  persistent_bottom_nav_bar:
  # pdfx:
  flutter_tts:
  # flutter_pdf_text:
  syncfusion_flutter_pdf:
  provider: ^6.1.4
  google_nav_bar: ^5.0.7
  font_awesome_flutter: ^10.8.0
  fluentui_icons: ^1.0.0
  hive_flutter: ^1.1.0
  animated_toggle_switch: ^0.8.4
  async: ^2.12.0
  syncfusion_flutter_datepicker: ^29.1.39
  flutter_html: ^3.0.0-beta.2
  iconsax_plus: 
  iconsax:
  custom_clippers:

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis:
  flutter_native_splash:
  change_app_package_name:
  hive_generator:
  build_runner:
  icons_launcher:

# flutter pub run flutter_launcher_icons
# flutter_icons:
#   #  image_path: "assets/images/Asset365 splash screen.png"
#   image_path: "assets/images/srmgrouplogo.png"
#   android: "launcher_icon"
#   ios:

icons_launcher:
  image_path: "assets/images/srmgrouplogo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  background_image: "assets/images/srmgroupsplash.png"
  android: true
  ios: true
  android_12:
    image: assets/images/srmgroupsplash.png

    color: "#FFFFFF"

    icon_background_color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
