name: sample

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  connectivity_plus:
  google_fonts: 
  flutter_riverpod:
  http:
  shared_preferences:
  intl:
  firebase_core:
  firebase_auth:
  firebase_analytics:
  firebase_messaging:
  cached_network_image:
  permission_handler:
  url_launcher:
  package_info_plus:
  device_info_plus:
  logger:
  awesome_notifications:
  flutter_svg: ^1.1.6
  dropdown_search:

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis:
  flutter_launcher_icons:
  flutter_native_splash:
  change_app_package_name:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
