name: sample

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  connectivity_plus:
  google_fonts: ^4.0.1
  flutter_riverpod:
  http:
  shared_preferences:
  intl:
  firebase_core:
  firebase_auth:
  firebase_analytics:
  firebase_messaging:
  cached_network_image:
  permission_handler:
  url_launcher:
  package_info_plus:
  device_info_plus:
  logger:
  awesome_notifications: ^0.8.2
  flutter_svg: ^1.1.6
  dropdown_search: ^5.0.5
  xml:
  encrypt:
  hex:
  flutter_styled_toast:
  wave:
  fluttertoast:
  liquid_pull_to_refresh:
  hive:
  # hive_flutter:
  path_provider:
  open_file:
  blinking_text:
  file_picker:
  flutter_pdfview:
  printing:
  pdf:
  flutter_cached_pdfview:
  excel:
  flicked_cards: ^0.0.3
  flutter_neumorphic:
  # animated_cards_carousel:
  carousel_slider:
  sidebarx:
  percent_indicator:
  flutter_zoom_drawer:
  badges:
  fl_chart:
  flutter_animate:
  table_calendar:
  d_chart:
  graphic:
  pie_chart:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis:
  flutter_launcher_icons:
  flutter_native_splash:
  change_app_package_name:
  hive_generator:
  build_runner:

# flutter pub run flutter_launcher_icons
flutter_icons:
  #  image_path: "assets/images/Asset365 splash screen.png"
  image_path: "assets/images/SRMLogo.png"
  android: "launcher_icon"
  ios: true

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  background_image: "assets/images/SRMSplashLogo.png"
  android: true
  ios: true
  android_12:
    image: assets/images/SRMSplashLogo.png

    color: "#FFFFFF"

    icon_background_color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
